doacao/urls.py
from django.urls import path

from .views import AgendamentoList, AgendamentoDetail, AgendamentoCreate, AgendamentoOk, AgendadosConsulta

app_name = 'doacao'

urlpatterns = [
    path('', AgendamentoList.as_view(), name='list'),
    path('<int:pk>/ver', AgendamentoDetail.as_view(), name='view'),
    path('doar/<int:pk>/', AgendamentoCreate.as_view(), name='doar'),
    path('ok$0bf082$03af301/', AgendamentoOk.as_view(), name='doacao_ok'),
    path('produto/<int:pk>/', AgendadosConsulta.as_view(), name='produto_list'),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('relatorios/', views.relatorios, name='relatorios'),
    path('produtos_grafico/', views.produtos_mais_doados, name='produtos_grafico'),
    path('cestas_doadas/', views.cestas_doadas, name='cestas_doadas'),
    path('renda_familiar/', views.renda_familiar, name='renda_familiar'),
    path('analise_familias/', views.analise_familias, name='analise_familias'),

]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt import views as jwt_views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

"""
Documentação da API
"""
schema_view = get_schema_view(
   openapi.Info(
      title="API Doação",
      default_version='v1',
      description='API de doação a partir de módulo "client" de terceiros',
      #terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@dummy.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('doacao/', include('doacao.urls', namespace='doacao')),
    path('recebimento/', include('recebimento.urls', namespace='recebimento')),
    path('cadastros/', include('cadastros.urls', namespace='cadastros')),
    path('api/v1/doacao/', include('doacaoapi.urls', namespace='doacaoapi')),

    # JWT Authentication
	path(
        'api/token/', 
        jwt_views.TokenObtainPairView.as_view(), 
        name ='token_obtain_pair'
    ),
	path(
        'api/token/refresh/', 
        jwt_views.TokenRefreshView.as_view(), 
        name ='token_refresh'
    ),
    path(
        'api/token/verify/', 
        jwt_views.TokenVerifyView.as_view(), 
        name ='token_verify'
    ),

    # API Documentation
    path('playground', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('docs', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    # deixar por último
    path('', include('pages.urls', namespace='pages')),
]

doacao/forms.py
from django import forms

from pages.models import Produto, DoacaoAgendada

class AgendamentoForm(forms.ModelForm):

    class Meta:
        model = DoacaoAgendada
        fields = ('produto', 'quantidade', )


    def __init__(self, *args, **kwargs):

        super(AgendamentoForm, self).__init__(*args, **kwargs)
        
        self.fields['quantidade'].widget.attrs['readonly'] = 'readonly'
        
        initial = kwargs.get('initial')
        grupoProduto = initial.get('grupoProduto')
        
        self.fields['produto'].queryset = Produto.objects.filter(
            grupoProduto=grupoProduto,
            aceitaDoacao=True
        )

doacao/views.py
from django.views.generic import ListView, CreateView, DetailView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from braces.views import GroupRequiredMixin

from pages.models import DoacaoAgendada 
from .forms import AgendamentoForm

from services.doacao_service import DoacaoService
from services.grupo_produto_service import GrupoProdutoService


class AgendamentoList(LoginRequiredMixin, ListView):
    
    model = DoacaoAgendada
    context_object_name = 'db'
    template_name = 'doacao/doacao_list.html'
    paginate_by = 10

    def get_queryset(self):
        return DoacaoService.itensCestas()


class AgendamentoDetail(GroupRequiredMixin, LoginRequiredMixin, DetailView):

    model = DoacaoAgendada
    context_object_name = 'db'
    template_name = 'doacao/doacao_view.html'
    group_required = 'admin_users'
    redirect_field_name = '/'


class AgendamentoCreate(LoginRequiredMixin, CreateView):
    
    model = DoacaoAgendada
    form_class = AgendamentoForm
    template_name = 'doacao/doacao_form.html'
    success_url = reverse_lazy('doacao:doacao_ok')

    grupoProduto = None


    def get_initial(self):
        self.grupoProduto = GrupoProdutoService().getById(self.kwargs.get('pk'))
        success_message = self.request.user.first_name
        return {
            'grupoProduto': self.grupoProduto,
        }


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['grupoProduto'] = self.grupoProduto
        return context


    def form_valid(self, form):
        form.instance.doador = self.request.user
        return super().form_valid(form)


class AgendamentoOk(LoginRequiredMixin, TemplateView):
    template_name = 'doacao/doacao_ok.html'


class AgendadosConsulta(GroupRequiredMixin, LoginRequiredMixin, ListView):
    
    model = DoacaoAgendada
    context_object_name = 'db'
    paginate_by = 10
    template_name = 'doacao/doacao_produto_list.html'
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_queryset(self):
        self.pk = self.kwargs.get('pk')
        return DoacaoService.listProdutoAgendados(self, self.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['grupoProdutoDescricao'] = DoacaoService.getNomeGrupoProduto(self, self.pk)
        return context

templates/doacao/doacao_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-12 m-auto text-left">
  <h3>Doação de Alimentos</h3>
</div>

<div class="col-12 m-auto pt-4">
    <form name="form" id="form" action="" method='post'>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary">Salvar</button>
        <a href="{% url 'doacao:list' %}" target="_self"
          class="btn btn-secondary ml-3" role="button">Cancelar</a>
    </form>
</div>    

{% endblock %}

templates/doacao/doacao_list.html
{% extends 'base.html' %}

{% block content %}

<div class="col-12 m-auto text-left">
  <h3>Doação de Alimentos</h3>
</div>

<div class="col-12 m-auto pt-4">
  <table class="table table-sm">
      <thead class="thead-light">
          <tr>
              <th scope="col">Descrição</th>
              <th scope="col" style="width: 150px" class="text-center">% Atingido</th>
              <th scope="col" style="width: 112px" class="text-center">Ação</th>
          </tr>
      </thead>
      <tbody>
          {% for dbs in db %}
              <tr>
                  <td class="align-middle">{{ dbs.descricao }}</td>
                  <td class="align-middle">
                    <div class="progress">
                        {% if dbs.percentual < 100 %}
                            <span class="sr-only" id="progresso_{{ forloop.counter }}" 
                                aria-label="{{ dbs.percentual }}% de {{ dbs.descricao }}"></span>
                            <div class="progress-bar bg-warning" style="width: {{ dbs.percentual }}%"></div>
                        {% else %}
                            <span class="sr-only" id="meta_ok_{{ forloop.counter }}" 
                                aria-label="100% de {{ dbs.descricao }}"></span>
                            <div class="progress-bar bg-info" style="width: 100%"></div>
                        {% endif %}
                    </div>                    
                  </td>
                  <td>
                      <a href="{% url 'doacao:doar' dbs.id %}" class="btn btn-sm btn-secondary" style="width: 100px" 
                        title="doar {{ dbs.descricao }}" role="button">Doar</a>
                  </td>
              </tr>
          {% endfor %}
      </tbody>
  </table>
  {% if is_paginated %}
  {% include "pagination.html" with page=page_obj %}
  {% endif %}
</div>    

{% endblock %}

templates/doacao/doacao_ok.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-12 align-self-center mt-2">
    <h3 class="display-4">Muito Obrigado!</h3>
  </div>
  <div class="col-12 align-self-center mb-3">
    <p class="text-justify lead">
        <h5>Agora você só precisa entregar sua doação na igreja.</h5>
    </p>
    <a href="{% url 'doacao:list' %}" target="_self"
      class="btn btn-secondary btn-lg mt-2" style="width: 200px" role="button">
      Finalizar
    </a>
  </div>
</div>
{% endblock %}

templates/doacao/doacao_produto_list.html
{% extends 'base.html' %}

{% block content %}

<div class="col-12 m-auto text-left">
    <h3>Doações do Produto</h3>
    <h4 class="ml-2 text-secondary" style="font-size: 1rem;">
        <em class="fas fa-angle-double-right mr-1"></em>
        {{ grupoProdutoDescricao }}
    </h4>
</div>

<div class="col-12 m-auto pt-2 text-right">
    <a href="{% url 'dashboard:view' %}" target="_self"
        class="btn btn-secondary" style="width: 100px" role="button">Voltar</a>
</div>

<div class="col-12 m-auto pt-2">
    <table class="table table-sm">
        <thead class="thead-light">
            <tr>
                <th scope="col">Agendado</th>
                <th scope="col">Qtde</th>
                <th scope="col">Doador</th>
                <th scope="col">STA</th>
                <th scope="col" class="text-center" style="width: 30px">Ação</th>
            </tr>
        </thead>
        <tbody>
            {% for dbs in db %}
                <tr {% if dbs.status == "PER" %}class="text-danger">{% endif %}>
                    <td class="align-middle">{{ dbs.dataAgendamento|date:"d/m" }}</td>
                    <td class="align-middle pl-3">{{ dbs.quantidade }}</td>
                    <td class="align-middle">{{ dbs.doador.username }}</td>
                    <td class="align-middle">{{ dbs.status }}</td>
                    <td class="text-center">
                        <a href="{% url 'doacao:view' dbs.id %}" class="pr-1" target="_self"
                            role="button" title="Abrir doação de {{ dbs.doador.username }}">
                            <em class="fas fa-eye"></em>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        <caption class="text-center">Coluna STA indica status da doação</caption>
    </table>
    {% if is_paginated %}
    {% include "pagination.html" with page=page_obj %}
    {% endif %}
</div>    

{% endblock %}

templates/doacao/doacao_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-12 m-auto text-left">
  <h3>Doações do Produto</h3>
</div>

<div class="col-12 m-auto pt-2 text-right">
  <a href="{% url 'doacao:produto_list' db.produto.grupoProduto.id %}" target="_self"
    class="btn btn-secondary" style="width: 100px" role="button">Voltar</a>
</div>

<div class="col-12 m-auto pt-2">

  <table class="table table-bordered">
    <tr>
      <td style="width: 100px">Produto</td>
      <td><strong>{{ db.produto.descricao }}</strong></td>
    </tr>
    <tr>
      <td>Quantidade</td>
      <td><strong>{{ db.quantidade }}</strong></td>
    </tr>
    <tr>
      <td>Doador </td>
      <td><strong>{{ db.doador.username }}</strong></td>
    </tr>
    <tr>
      <td>Status</td>
      <td><strong>{{ db.get_status_display }}</strong></td>
    </tr>
    <tr>
      <td>Agendamento </td>
      <td><strong>{{ db.dataAgendamento|date:"d/m/y" }}</strong></td>
    </tr>
  </table>

</div>    

{% endblock %}