cadastros/urls.py
from django.urls import path

from .views import FamiliaAtendidaCreate, FamiliaAtendidaDelete, FamiliaAtendidaEdit, FamiliaAtendidaList
from .views import GrupoProdutoList, GrupoProdutoEdit, GrupoProdutoCreate, GrupoProdutoDelete, FamiliaAtendidaQuestionario
from .views import UnidadeOrganizacaoEdit, ProdutoList, ProdutoEdit, ProdutoCreate, ProdutoDelete

app_name = 'cadastros'

urlpatterns = [
    path('unidadeorg/<int:pk>/', UnidadeOrganizacaoEdit.as_view(), name='unidade_org_edit'),
    path('familiaatendida/', FamiliaAtendidaList.as_view(), name='familia_atendida_list'),
    path('familiaatendida/novo', FamiliaAtendidaCreate.as_view(), name='familia_atendida_create'),
    path('familiaatendida/<int:pk>/', FamiliaAtendidaEdit.as_view(), name='familia_atendida_edit'),
    path('familiaatendida/<int:pk>/delete', FamiliaAtendidaDelete.as_view(), name='familia_atendida_delete'),
    path('familiaatendida/<int:pk>/questionario', FamiliaAtendidaQuestionario.as_view(), name='familia_atendida_question'),
    path('grupoproduto/', GrupoProdutoList.as_view(), name='grupo_produto_list'),
    path('grupoproduto/novo', GrupoProdutoCreate.as_view(), name='grupo_produto_create'),
    path('grupoproduto/<int:pk>/', GrupoProdutoEdit.as_view(), name='grupo_produto_edit'),
    path('grupoproduto/<int:pk>/delete', GrupoProdutoDelete.as_view(), name='grupo_produto_delete'),
    path('produto/', ProdutoList.as_view(), name='produto_list'),
    path('produto/novo', ProdutoCreate.as_view(), name='produto_create'),
    path('produto/<int:pk>/', ProdutoEdit.as_view(), name='produto_edit'),
    path('produto/<int:pk>/delete', ProdutoDelete.as_view(), name='produto_delete'),
]

doacao/urls.py
from django.urls import path

from .views import AgendamentoList, AgendamentoDetail, AgendamentoCreate, AgendamentoOk, AgendadosConsulta

app_name = 'doacao'

urlpatterns = [
    path('', AgendamentoList.as_view(), name='list'),
    path('<int:pk>/ver', AgendamentoDetail.as_view(), name='view'),
    path('doar/<int:pk>/', AgendamentoCreate.as_view(), name='doar'),
    path('ok$0bf082$03af301/', AgendamentoOk.as_view(), name='doacao_ok'),
    path('produto/<int:pk>/', AgendadosConsulta.as_view(), name='produto_list'),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('relatorios/', views.relatorios, name='relatorios'),
    path('produtos_grafico/', views.produtos_mais_doados, name='produtos_grafico'),
    path('cestas_doadas/', views.cestas_doadas, name='cestas_doadas'),
    path('renda_familiar/', views.renda_familiar, name='renda_familiar'),
    path('analise_familias/', views.analise_familias, name='analise_familias'),

]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt import views as jwt_views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

"""
Documentação da API
"""
schema_view = get_schema_view(
   openapi.Info(
      title="API Doação",
      default_version='v1',
      description='API de doação a partir de módulo "client" de terceiros',
      #terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@dummy.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('doacao/', include('doacao.urls', namespace='doacao')),
    path('recebimento/', include('recebimento.urls', namespace='recebimento')),
    path('cadastros/', include('cadastros.urls', namespace='cadastros')),
    path('api/v1/doacao/', include('doacaoapi.urls', namespace='doacaoapi')),

    # JWT Authentication
	path(
        'api/token/', 
        jwt_views.TokenObtainPairView.as_view(), 
        name ='token_obtain_pair'
    ),
	path(
        'api/token/refresh/', 
        jwt_views.TokenRefreshView.as_view(), 
        name ='token_refresh'
    ),
    path(
        'api/token/verify/', 
        jwt_views.TokenVerifyView.as_view(), 
        name ='token_verify'
    ),

    # API Documentation
    path('playground', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('docs', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    # deixar por último
    path('', include('pages.urls', namespace='pages')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Semana da Partilha{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-secondary bg-secondary mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}" target="_self">
                    Matriz São José Operário
                </a>
                {% if user.is_authenticated %}
                    {% if user.administrador %}
                        <div class="btn-group" role="menubar">
                            <button type="button" class="btn btn-light">Admin</button>
                            <button type="button" class="btn btn-light dropdown-toggle dropdown-toggle-split" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="{% url 'dashboard:view' %} " role="menuitem" target="_self">Dashboard</a>
                            <div class="dropdown-divider" role="link"></div>
                            <a class="dropdown-item" href="{% url 'doacao:list' %}" role="menuitem" target="_self">Doação de Alimentos</a>
                            <a class="dropdown-item" href="{% url 'recebimento:list' %}" role="menuitem" target="_self">Recebimento de Doação</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'cadastros:familia_atendida_list' %}" role="menuitem" target="_self">Famílias Atendidas</a>
                            <a class="dropdown-item" href="{% url 'cadastros:grupo_produto_list' %}" role="menuitem" target="_self">Grupos de Produtos</a>
                            <a class="dropdown-item" href="{% url 'cadastros:produto_list' %}" role="menuitem" target="_self">Produtos</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'cadastros:unidade_org_edit' 1 %}" role="menuitem" target="_self">Configurações</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'pages:relatorios' %}" role="menuitem" target="_self">Relatórios</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'account_logout' %}" role="menuitem" target="_self">Sair da Aplicação</a>
                            </div>
                        </div>
                    {% else %}
                        <a href="{% url 'account_logout' %}" class="btn btn-light" style="width: 90px" role="button" target="_self">Sair</a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'dashboard:view' %}" class="btn btn-light" style="width: 80px" role="button" target="_self">Admin</a>
                {% endif %}    
            </div>
        </nav>
    </header>
    {% if messages %}
    <div class="container messages">
        {% for message in messages %}
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="{% static 'js/javascript.js' %}"></script>
</body>
</html>

templates/graficos_base.html
{% extends 'base.html' %}

{% block content %}

<h2>{{titulo}}</h2>

{% include './graph_chart.html' %}


{% endblock content %}

templates/graph_chart.html
<div id="container" style="width: 75%;">
    <canvas id="pie-chart"></canvas>
  </div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>

var config = {
    type: '{{chart_type}}',
    data: {
        datasets: [{
            data: {{ data|safe }},
            backgroundColor: [
                {% for value in data %}
                '#123456', '#654321', '#AABBCC', '#CCBBAA', '#ABCDEF',
                {% endfor %}
            ],
            label: '{{legenda}}'
        }],
        labels: {{ labels|safe }}
    },
    options: {
    responsive: true
    }
};

window.onload = function() {
    var ctx = document.getElementById('pie-chart').getContext('2d');
    window.myPie = new Chart(ctx, config);
};

</script>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
      <div class="col-12 align-self-center mt-5">
        <h1 class="display-3">Bem-vindo!</h1>
      </div>
      <div class="col-12 align-self-center mt-3 mb-3">
        <p class="text-justify lead">
            <h4>Caridade, principal caminho da vida do cristão.</h4>
        </p>
      </div>
      <div class="col-12 align-self-center">
        <p class="text-justify">
            Convidamos você a participar conosco do programa de doação de alimentos
            que tem como objetivo ajudar nossos irmãos que estão passando por algum
            momento de dificuldade.
        </p>
        <a href="{% url 'doacao:list' %}" class="btn btn-secondary btn-lg" style="width: 290px" target="_self">
            Quero fazer uma doação!
        </a>
        <div class="col-12 align-self-center pl-0 mt-2">
            <a href="{% url 'account_signup' %}" target="_self" style="color: black">ou clique aqui se ainda não é cadastrado</a>
        </div>
      </div>
    </div>
{% endblock %}

templates/pagination.html
<div class="text-center mb-3 paginacao">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}" aria-label="Página anterior"
        role="button" target="_self"><em class="fas fa-caret-square-left"></em></a>
    {% else %}
    <em class="fas fa-caret-square-left text-secondary"></em>
    {% endif %}
    Página {{ page.number }}/{{ page.paginator.num_pages }}
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}" aria-label="Próxima página" 
        role="button" target="_self"><em class="fas fa-caret-square-right"></em></a>
    {% else %}
    <em class="fas fa-caret-square-right text-secondary"></em>
    {% endif %}
</div>

templates/produtos_grafico.html
{% extends 'base.html' %}

{% block content %}

<h2>Grafico de produtos mais doados</h2>

{% include './graph_chart.html' %}


{% endblock content %}

templates/relatorio_analise_familias.html
{% extends 'base.html' %}

{% block content %}

<h2>Dados Gerais</h2>

<div style="line-height: 1em; margin-top: 40px;">

<p>Total de familias cadastradas: {{tot_familias}}</p>
<br>
<p>Total de Familias que responderam ao questionario socioeconômico: {{tot_quest_familias}}</p>
<p>Total de membros familiares: {{tot_membros}}</p>
<hr>
<br>

<p>Familias que consideram seu bairro perigoso: {{perigoso}}%</p>
<p>Famílias com crianças: {{kids}}%</p>
<p>Crianças que frequentam escola: {{kids_escola}}%</p>
<p>Membros familiares com trabalho informal: {{trab_informal}}% </p>
<br>
<p>Grau de escolaridade dos membros adultos das familias:</p>
<ul style="margin-left: -10px;">
<p>Fundamental Incompleto: {{fun_in}}%</p>
<p>Fundamental Completo: {{fun_cp}}%</p>
<p>Médio Incompleto: {{med_in}}%</p>
<p>Médio Completo: {{med_cp}}%</p>
<p>Superior Incompleto: {{sup_in}}%</p>
<p>Superior Completo : {{sup_cp}}%</p>
<p>Não informado: {{sem_dados}}%</p>
</ul>
<br>

<p>Familias que recebem auxilio do Governo: {{gov_auxilio}}%</p>

<br>
<p style="font-size: 0.9em; color:gray; margin-top:20px;">Observação: é usado como base o total de Famílias e não apenas as que responderam ao questionario</p>

</div>
{% endblock %}

templates/relatorios.html
{% extends 'base.html' %}

{% block content %}
<h2>Relatórios</h2>

<ul class="relatorios_list" style="margin-top: 30px">
    <li><a style="color: black" href="{% url 'pages:produtos_grafico' %}">Produtos mais doados</a></li>
    <li><a style="color: black" href="{% url 'pages:cestas_doadas' %}">Cestas Doadas</a></li>
    <li><a style="color: black" href="{% url 'pages:renda_familiar' %}">Renda Familiar</a></li>
    <li><a style="color: black" href="{% url 'pages:analise_familias' %}">Análise das famílias assistidas</a></li>
</ul>

{% endblock %}