dashboard/urls.py
from django.urls import path

from .views import DashboardView, FechaCestaView, FechaCestaUpdate

app_name = 'dashboard'

urlpatterns = [
    path('', DashboardView.as_view(), name='view'),
    path('f3ch4_c3$t4_n2p@a&fn8i3n', FechaCestaView.as_view(), name="fcesta"),
    path('f3ch4_c3$t4_n3r@aw8i0$4x', FechaCestaUpdate.as_view(), name="updcesta")
]

doacao/urls.py
from django.urls import path

from .views import AgendamentoList, AgendamentoDetail, AgendamentoCreate, AgendamentoOk, AgendadosConsulta

app_name = 'doacao'

urlpatterns = [
    path('', AgendamentoList.as_view(), name='list'),
    path('<int:pk>/ver', AgendamentoDetail.as_view(), name='view'),
    path('doar/<int:pk>/', AgendamentoCreate.as_view(), name='doar'),
    path('ok$0bf082$03af301/', AgendamentoOk.as_view(), name='doacao_ok'),
    path('produto/<int:pk>/', AgendadosConsulta.as_view(), name='produto_list'),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('relatorios/', views.relatorios, name='relatorios'),
    path('produtos_grafico/', views.produtos_mais_doados, name='produtos_grafico'),
    path('cestas_doadas/', views.cestas_doadas, name='cestas_doadas'),
    path('renda_familiar/', views.renda_familiar, name='renda_familiar'),
    path('analise_familias/', views.analise_familias, name='analise_familias'),

]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt import views as jwt_views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

"""
Documentação da API
"""
schema_view = get_schema_view(
   openapi.Info(
      title="API Doação",
      default_version='v1',
      description='API de doação a partir de módulo "client" de terceiros',
      #terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@dummy.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('doacao/', include('doacao.urls', namespace='doacao')),
    path('recebimento/', include('recebimento.urls', namespace='recebimento')),
    path('cadastros/', include('cadastros.urls', namespace='cadastros')),
    path('api/v1/doacao/', include('doacaoapi.urls', namespace='doacaoapi')),

    # JWT Authentication
	path(
        'api/token/', 
        jwt_views.TokenObtainPairView.as_view(), 
        name ='token_obtain_pair'
    ),
	path(
        'api/token/refresh/', 
        jwt_views.TokenRefreshView.as_view(), 
        name ='token_refresh'
    ),
    path(
        'api/token/verify/', 
        jwt_views.TokenVerifyView.as_view(), 
        name ='token_verify'
    ),

    # API Documentation
    path('playground', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('docs', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    # deixar por último
    path('', include('pages.urls', namespace='pages')),
]

dashboard/views.py
from django.views.generic import TemplateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin
from django.shortcuts import redirect
from django.http import HttpResponse

from services.doacao_service import DoacaoService

class DashboardView(GroupRequiredMixin, LoginRequiredMixin, TemplateView):

    template_name = 'dashboard/dashboard.html'
    group_required = 'admin_users'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)

        cestas = DoacaoService.cestas()

        context['cestasCompletas'] = cestas[0]
        context['cestasAgendadas'] = cestas[1]
        context['db'] = cestas[2]

        return context



class FechaCestaView(GroupRequiredMixin, LoginRequiredMixin, TemplateView):

    template_name = 'dashboard/fecha_ok.html'
    group_required = 'admin_users'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):

        context = super(FechaCestaView, self).get_context_data(**kwargs)
        cestas = DoacaoService.cestas()
        context['cestasCompletas'] = cestas[0]

        return context



class FechaCestaUpdate(GroupRequiredMixin, LoginRequiredMixin, View):

    group_required = 'admin_users'
    redirect_field_name = 'redirect_to'

    def post(self, request):
        DoacaoService.fecharCestas()
        return redirect('dashboard:view')
        

templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="col-12 m-auto pt-4">

  <div class="row">
    <div class="col-sm-6" role="contentinfo">
      <div class="card bg-light mb-3">
        <div class="card-body">
          <h5 class="card-title text-primary" 
            aria-label="{{ cestasCompletas }} cestas completas, baseado nas doações recebidas">Cestas Completas</h5>
          <div class="row">
            <div class="col-4" aria-hidden="true">
              <div style="font-size: 2rem"><span class="badge badge-primary">{{ cestasCompletas }}</span></div>
            </div>
            <div class="col-8 text-right">
              <a href="{% url 'dashboard:fcesta' %}" class="btn btn-secondary" role="button" target="_self">Fechar as Cestas</a>
            </div>
          </div>          
        </div>
        <div class="card-footer text-dark" aria-hidden="true" style="font-size: 1.1rem">Baseado nas doações recebidas</div>
      </div>
    </div>
    <div class="col-sm-6" role="contentinfo">
      <div class="card bg-light mb-3">
        <div class="card-body">
          <h5 class="card-title text-info"
            aria-label="{{ cestasAgendadas }} cestas agendadas, baseado nas doações agendadas">Cestas Agendadas</h5>
          <div aria-hidden="true" style="font-size: 2rem"><span class="badge badge-info">{{ cestasAgendadas }}</span></div>
        </div>
        <div class="card-footer text-dark" aria-hidden="true" style="font-size: 1.1rem">Baseado nas doações agendadas</div>
      </div>
    </div>
  </div>
    
  <table class="table table-sm">
      <thead class="thead-light">
          <tr>
              <th scope="col">Descrição</th>
              <th scope="col" style="width: 35px">Age</th>
              <th scope="col" style="width: 35px">Rec</th>
              <th scope="col" style="width: 60px" class="text-center">Meta</th>
              <th scope="col" style="width: 60px" class="text-center">Ação</th>
          </tr>
      </thead>
      <tbody>
          {% for dbs in db %}
              <tr>
                  <td class="align-middle">{{ dbs.descricao }}</td>
                  <td class="align-middle text-right">{{ dbs.agendado }}</td>
                  <td class="align-middle text-right">{{ dbs.recebido }}</td>
                  <td class="align-middle">
                    <div class="progress">
                        {% if dbs.percentual < 100 %}
                            <span class="sr-only" aria-label="{{ dbs.percentual }}% de {{ dbs.descricao }}"></span>
                            <div class="progress-bar bg-warning" style="width: {{ dbs.percentual }}%"></div>
                        {% else %}
                            <div class="progress-bar bg-info" style="width: 100%"></div>
                        {% endif %}
                    </div>
                  </td>
                  <td class="align-middle">
                    {% if dbs.agendado != 0 %}
                      <a href="{% url 'doacao:produto_list' dbs.id %}" target="_self"
                        title="consultar doações de {{ dbs.descricao }}" role="button">
                        <em class="fas fa-user-clock text-info"></em></a>
                    {% else %}
                      <em class="fas fa-user-clock" style="color: silver"></em>
                    {% endif %}
                    {% if dbs.recebido != 0 %}
                      <a href="{% url 'recebimento:produto_list' dbs.id %}" target="_self"
                        title="consultar recebimentos de {{ dbs.descricao }}" role="button">
                        <em class="fas fa-truck text-primary ml-1"></em></a>
                    {% else %}
                      <em class="fas fa-truck ml-1" style="color: silver"></em>
                    {% endif %}
                  </td>
              </tr>
          {% endfor %}
      </tbody>
      <caption class="text-center">Coluna "Age" = doações agendadas &nbsp;&nbsp;::&nbsp;&nbsp; Coluna "Rec" = doações recebidas</caption>
  </table>
</div>    

{% endblock %}

templates/dashboard/fecha_ok.html
{% extends 'base.html' %}

{% block content %}

<div class="col-12 p-0 text-left">
  <h3>Fechamento das Cestas</h3>
</div>

<div class="row">
  <div class="col-sm-6 mt-4 mb-5">
    <div class="card bg-light">
      <div class="card-body">
        <h4 class="card-title text-primary" 
          aria-label="{{ cestasCompletas }} cestas completas">Cestas Completas</h4>
        <div class="row">
          <div class="col-6">
            <div aria-hidden="true" style="font-size: 2rem"><span class="badge badge-primary">{{ cestasCompletas }}</span></div>
          </div>
        </div>          
      </div>
    </div>
  </div>

  <div class="col-12 align-self-center">
        <p style="font-size: 2rem" role="dialog">Confirma?</p>
  </div>

  <div class="col-12 align-self-center">
    <p class="mb-4">
      Será iniciado um novo ciclo de doações.<br>
      Deseja realmente prosseguir?
    </p>
    <form action="{% url 'dashboard:updcesta' %}" method="POST">
      {% csrf_token %}
      <button type="submit" class="btn btn-secondary btn-sm">OK</button>
      <a href="{% url 'dashboard:view' %}" target="_self"
        class="btn btn-secondary btn-sm" style="width: 100px" role="button">
        Cancelar
      </a>
  </form>
  </div>
</div>

{% endblock %}