pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('relatorios/', views.relatorios, name='relatorios'),
    path('produtos_grafico/', views.produtos_mais_doados, name='produtos_grafico'),
    path('cestas_doadas/', views.cestas_doadas, name='cestas_doadas'),
    path('renda_familiar/', views.renda_familiar, name='renda_familiar'),
    path('analise_familias/', views.analise_familias, name='analise_familias'),

]

recebimento/urls.py
from django.urls import path

from .views import RecebimentoList, RecebimentoDetail, RecebimentoCreate, RecebidosConsulta

app_name = 'recebimento'

urlpatterns = [
    path('', RecebimentoList.as_view(), name='list'),
    path('<int:pk>/ver', RecebimentoDetail.as_view(), name='view'),
    path('direta/', RecebimentoCreate.as_view(), name='direta'),
    path('agendada/<int:pk>/', RecebimentoCreate.as_view(), name='agendada'),
    path('produto/<int:pk>/', RecebidosConsulta.as_view(), name='produto_list'),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt import views as jwt_views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

"""
Documentação da API
"""
schema_view = get_schema_view(
   openapi.Info(
      title="API Doação",
      default_version='v1',
      description='API de doação a partir de módulo "client" de terceiros',
      #terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@dummy.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('doacao/', include('doacao.urls', namespace='doacao')),
    path('recebimento/', include('recebimento.urls', namespace='recebimento')),
    path('cadastros/', include('cadastros.urls', namespace='cadastros')),
    path('api/v1/doacao/', include('doacaoapi.urls', namespace='doacaoapi')),

    # JWT Authentication
	path(
        'api/token/', 
        jwt_views.TokenObtainPairView.as_view(), 
        name ='token_obtain_pair'
    ),
	path(
        'api/token/refresh/', 
        jwt_views.TokenRefreshView.as_view(), 
        name ='token_refresh'
    ),
    path(
        'api/token/verify/', 
        jwt_views.TokenVerifyView.as_view(), 
        name ='token_verify'
    ),

    # API Documentation
    path('playground', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('docs', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    # deixar por último
    path('', include('pages.urls', namespace='pages')),
]

recebimento/forms.py
from django import forms
from django.forms.fields import DateField

from pages.models import Produto, DoacaoRecebida
from users.models import User

class EntradaAgendadaForm(forms.ModelForm):

    class Meta:
        model = DoacaoRecebida
        fields = ('doador', 'produto', 'quantidade', 'dataRecebimento', 'dataValidade', )


    def __init__(self, *args, **kwargs):

        super(EntradaAgendadaForm, self).__init__(*args, **kwargs)

        self.fields['dataValidade'].widget.attrs['placeholder'] = '00/00/0000'
        self.fields['dataRecebimento'].widget.attrs['placeholder'] = '00/00/0000'
        
        initial = kwargs.get('initial')
        if initial is None:
            self.fields['doador'].queryset = User.objects.filter(administrador=False)
            self.fields['produto'].queryset = Produto.objects.filter(aceitaDoacao=True)
            self.fields['produto'].widget.attrs['autofocus'] = 'autofocus'
            return

        produto = initial.get('produto')
        doador = initial.get('doador')

        self.fields['produto'].queryset = Produto.objects.filter(id=produto.id)
        self.fields['doador'].queryset = User.objects.filter(id=doador.id)
        self.fields['produto'].empty_label = None
        self.fields['doador'].empty_label = None

        # Produto, quantidade e doador não pode ser mudado, vem do agendamento
        self.fields['dataValidade'].widget.attrs['autofocus'] = 'autofocus'
        self.fields['quantidade'].widget.attrs['readonly'] = 'readonly'
        self.fields['produto'].widget.attrs['readonly'] = 'readonly'
        self.fields['doador'].widget.attrs['readonly'] = 'readonly'

recebimento/views.py
from django.db import transaction
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

from braces.views import GroupRequiredMixin

from pages.models import DoacaoAgendada, DoacaoRecebida

from .forms import EntradaAgendadaForm

from services.doacao_service import DoacaoService


class RecebimentoList(GroupRequiredMixin, LoginRequiredMixin, ListView):
    
    model = DoacaoAgendada
    context_object_name = 'db'
    paginate_by = 10
    template_name = 'recebimento/recebimento_list.html'
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_queryset(self):

        search = self.request.GET.get('search')
        field = self.request.GET.get('field')

        if search:
            if field == 'd':
                return DoacaoService.listByDoador(self, search)
            else:
                return DoacaoService.listByProduto(self, search)

        return DoacaoService.listAll()


class RecebimentoDetail(GroupRequiredMixin, LoginRequiredMixin, DetailView):

    model = DoacaoRecebida
    context_object_name = 'db'
    template_name = 'recebimento/recebimento_view.html'
    group_required = 'admin_users'
    redirect_field_name = '/'


class RecebimentoCreate(GroupRequiredMixin, LoginRequiredMixin, CreateView):

    model = DoacaoRecebida
    form_class = EntradaAgendadaForm
    template_name = 'recebimento/recebimento_form.html'
    success_url = reverse_lazy('recebimento:list')
    group_required = 'admin_users'
    redirect_field_name = '/'

    doacaoAgendada = None


    def get_initial(self):

        if self.kwargs.get('pk') is None: return
        self.doacaoAgendada = DoacaoService.getById(self, self.kwargs.get('pk'))

        return {
            'doacaoAgendada': self.doacaoAgendada,
            'produto': self.doacaoAgendada.produto,
            'doador': self.doacaoAgendada.doador
        }

    @transaction.atomic
    def form_valid(self, form):

        if self.doacaoAgendada:
            self.doacaoAgendada.status = 'REC'
            self.doacaoAgendada.save()

        form.instance.doador = self.request.user
        return super().form_valid(form)


class RecebidosConsulta(GroupRequiredMixin, LoginRequiredMixin, ListView):
    
    model = DoacaoRecebida
    context_object_name = 'db'
    paginate_by = 10
    template_name = 'recebimento/recebimento_produto_list.html'
    group_required = 'admin_users'
    redirect_field_name = '/'

    def get_queryset(self):
        self.pk = self.kwargs.get('pk')
        return DoacaoService.listProdutoRecebimentos(self, self.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['grupoProdutoDescricao'] = DoacaoService.getNomeGrupoProduto(self, self.pk)
        return context

templates/recebimento/recebimento_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-12 m-auto text-left">
  <h3>Entrada de Doação de Alimentos</h3>
</div>

<div class="col-12 m-auto pt-4">
    <form name="form" id="form" action="" method='post'>
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-secondary">Salvar</button>
        <a href="{% url 'recebimento:list' %}" target="_self"
          class="btn btn-secondary ml-3">Cancelar</a>
    </form>
</div>    

{% endblock %}

templates/recebimento/recebimento_list.html
{% extends 'base.html' %}

{% block content %}

<div class="col-12 m-auto text-left">
  <h3>Entrada de Doação de Alimentos</h3>
</div>

<div class="col-12 m-auto pt-2 text-right">
    <span class="sr-only" id="btn_nao_agendada" aria-label="Adicionar um recebimento cuja doação não foi agendada" aria-hidden="true"></span>
    <a href="{% url 'recebimento:direta' %}" class="btn btn-secondary" role="button" aria-labelledby="btn_nao_agendada">Adicionar não Agendada</a>
</div>

<div class="col-12 m-auto pt-2">
    <form method="get" style="margin-bottom: 8px">

        <fieldset>
            <div class="form-check-inline">
                <label class="form-check-label" aria-label="Pesquisar por produto" for="por-produto">
                    <span class="sr-only" aria-hidden="true">Por Produto</span>
                    <input type="radio" class="form-check-input" id="por-produto" name="field" value="p" checked>Por Produto
                </label>
            </div>
            <div class="form-check-inline">
                <label class="form-check-label" aria-label="Pesquisar por doador" for="por-doador">
                <span class="sr-only" aria-hidden="true">Por Doador</span>
                <input type="radio" class="form-check-input" id="por-doador" name="field" value="d">Por Doador
                </label>
            </div>
        </fieldset>
        <label for="search" class="sr-only" aria-hidden="true">Pesquisar:</label>
        <input type="text" id="search" name="search" class="form-control mt-1" placeholder="Nome a pesquisar" 
        aria-label="informe o nome a pesquisar">
    </form>
    <div class="p-1 mb-1 bg-secondary text-white text-center" style="font-size: 1.2rem" role="heading">
        Doações Agendadas
    </div>
    <table class="table table-sm">
        <thead class="thead-light">
            <tr>
                <th scope="col">Produto</th>
                <th scope="col">Doador</th>
                <th scope="col" style="width: 75px" class="text-center">Ação</th>
            </tr>
        </thead>
        <tbody>
            {% for dbs in db %}
                <tr>
                    <td class="align-middle">{{ dbs.produto.descricao }}</td>
                    <td class="align-middle">{{ dbs.doador.username }}</td>
                    <td>
                        <span class="sr-only" id="btn_{{ forloop.counter }}" aria-hidden="true"
                            aria-label="receber {{ dbs.produto.descricao }} doado por {{ dbs.doador.username }}"></span>
                        <a href="{% url 'recebimento:agendada' dbs.id %}" class="btn btn-sm btn-secondary" role="button"
                            aria-labelledby="btn_{{ forloop.counter }}">Receber</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
    {% include "pagination.html" with page=page_obj %}
    {% endif %}
</div>    

{% endblock %}

templates/recebimento/recebimento_produto_list.html
{% extends 'base.html' %}

{% block content %}

<div class="col-12 m-auto text-left">
    <h3>Recebimentos do Produto</h3>
    <h4 class="ml-2 text-secondary" style="font-size: 1rem;">
        <em class="fas fa-angle-double-right mr-1"></em>
        {{ grupoProdutoDescricao }}
    </h4>
</div>

<div class="col-12 m-auto pt-2 text-right">
    <a href="{% url 'dashboard:view' %}" target="_self"
        class="btn btn-secondary" style="width: 100px" role="button">Voltar</a>
</div>

<div class="col-12 m-auto pt-2">
    <table class="table table-sm">
        <thead class="thead-light">
            <tr>
                <th scope="col">Entrada</th>
                <th scope="col">Qtde</th>
                <th scope="col">Doador</th>
                <th scope="col">STA</th>
                <th scope="col">Baixa</th>
                <th scope="col" class="text-center" style="width: 30px">Ação</th>
            </tr>
        </thead>
        <tbody>
            {% for dbs in db %}
                <tr {% if dbs.status == "PER" %}class="text-danger">{% endif %}>
                    <td class="align-middle">{{ dbs.dataRecebimento|date:"d/m" }}</td>
                    <td class="align-middle pl-3">{{ dbs.quantidade }}</td>
                    <td class="align-middle">{{ dbs.doador.username }}</td>
                    <td class="align-middle">{{ dbs.status }}</td>
                    <td class="align-middle">{{ dbs.dataBaixa|date:"d/m" }}</td>
                    <td class="text-center">
                        <a href="{% url 'recebimento:view' dbs.id %}" target="_self"
                            title="Abrir recebimento de {{ dbs.doador.username }}"
                            class="pr-1" role="button">
                            <em class="fas fa-eye"></em>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        <caption class="text-center">Coluna STA indica status do recebimento</caption>
    </table>
    {% if is_paginated %}
    {% include "pagination.html" with page=page_obj %}
    {% endif %}
</div>    

{% endblock %}

templates/recebimento/recebimento_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-12 m-auto text-left">
  <h3>Recebimentos do Produto</h3>
</div>

<div class="col-12 m-auto pt-2 text-right">
  <a href="{% url 'recebimento:produto_list' db.produto.grupoProduto.id %}" target="_self"
    class="btn btn-secondary" style="width: 100px" role="button">Voltar</a>
</div>

<div class="col-12 m-auto pt-2">

  <table class="table table-bordered">
    <tr>
      <td style="width: 100px">Produto</td>
      <td><strong>{{ db.produto.descricao }}</strong></td>
    </tr>
    <tr>
      <td>Quantidade</td>
      <td><strong>{{ db.quantidade }}</strong></td>
    </tr>
    <tr>
      <td>Validade</td>
      <td><strong>{{ db.dataValidade|date:"d/m/y" }}</strong></td>
    </tr>
    <tr>
      <td>Entrada</td>
      <td><strong>{{ db.dataRecebimento|date:"d/m/y" }}</strong></td>
    </tr>
    <tr>
      <td>Doador </td>
      <td><strong>{{ db.doador.username }}</strong></td>
    </tr>
    <tr>
      <td>Status</td>
      <td><strong>{{ db.get_status_display }}</strong></td>
    </tr>
    <tr>
      <td>Baixa</td>
      <td><strong>{{ db.dataBaixa|date:"d/m/y" }}</strong></td>
    </tr>
    <tr>
      <td>Via Web?</td>
      <td><strong>{{ db.doacaoViaWeb|yesno:"Sim,Não" }}</strong></td>
    </tr>
    <tr>
      <td>Saldo?</td>
      <td><strong>{{ db.saldoDeEntrega|yesno:"Sim,Não" }}</strong></td>
    </tr>
  </table>

</div>    

{% endblock %}